<a href="https://colab.research.google.com/github/LZY199/PracticalAI/blob/main/NumPy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# By setting seed(can be any value), to ensure always get the same random number(as long as the seed value is the same)
np.random.seed(1234)

In [4]:
#scalars
x = np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
#array
x = np.array([1.3, 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [1.3 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [7]:
#array
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape:  (3, 3)
x size:  9
x dtype:  int64


In [9]:
#functions
print("np.zeros((2,2)):\n", np.zeros((2,2)))
print("np.ones((2,2)):\n", np.ones((2,2)))
print("np.eye((2)):\n", np.eye((2)))
print("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]
