<a href="https://colab.research.google.com/github/LZY199/PracticalAI/blob/main/NumPy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
# By setting seed(can be any value), to ensure always get the same random number(as long as the seed value is the same)
np.random.seed(1234)

In [11]:
#scalars
x = np.array(6)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [12]:
#1 dimension array
x = np.array([1.3, 2.2, 1.7])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [1.3 2.2 1.7]
x ndim:  1
x shape:  (3,)
x size:  3
x dtype:  float64


In [13]:
#2 dimension array
x = np.array([[1,2,3], [4,5,6]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [[1 2 3]
 [4 5 6]]
x ndim:  2
x shape:  (2, 3)
x size:  6
x dtype:  int64


In [48]:
#3 dimension array
#Notes:
#shape(m,n,k...) means:
# In the array, from the most outsdie bracket, there are "m" elements who has "n" elements who has "k" elements......
x = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape) 
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
x ndim:  3
x shape:  (2, 2, 3)
x size:  12
x dtype:  int64


In [15]:
#functions
print("np.zeros((2,2)):\n", np.zeros((2,2)))
print("np.ones((2,2)):\n", np.ones((2,2)))
print("np.eye((2)):\n", np.eye((2)))
print("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [16]:
#indexing
#slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1,2 & cols 1,2: \n", x[0:3, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [21]:
#Int array indexing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print("len(x): ", len(x))
rows_to_get = np.arange(len(x))
print("rows_to_get:", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print("clos_to_get:", cols_to_get)
print("indexed elements in x:", x[rows_to_get, cols_to_get]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
len(x):  3
rows_to_get: [0 1 2]
clos_to_get: [0 2 1]
indexed elements in x: [ 1  7 10]


In [26]:
#boolean array indexing
x = np.array([[1,2],[3,4],[5,6]])
print("x:\n", x)
print("x>2:\n", x>2)
print("x[x>2]:\n", x[(x>2) & (x<6)])

x:
 [[1 2]
 [3 4]
 [5 6]]
x>2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x>2]:
 [3 4 5]


In [30]:
# numpy math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[1,2],[3,4]], dtype=np.float64)
print("x:\n", x)
print("y:\n", y)
print("x*y:\n", np.multiply(x,y)) #array multiplication
print("x.dot(y):\n", x.dot(y)) #matrix multiplication

x:
 [[1. 2.]
 [3. 4.]]
y:
 [[1. 2.]
 [3. 4.]]
x*y:
 [[ 1.  4.]
 [ 9. 16.]]
x.dot(y):
 [[ 7. 10.]
 [15. 22.]]


In [28]:
#dot production
a = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
b = np.array([[7,8], [9,10], [11,12]], dtype=np.float64)
print("a:\n", a)
print("b:\n", b)
print(a.dot(b))

a:
 [[1. 2. 3.]
 [4. 5. 6.]]
b:
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
[[ 58.  64.]
 [139. 154.]]


In [38]:
# sum 
# From the most outside bracket, axis = 0, 1, 2.....
x = np.array([[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]])
print (x)
print ("sum all: ", np.sum(x)) # sum of all elements
print ("sum by axis 0: ", np.sum(x, axis=0)) 
print ("sum by axis 1: ", np.sum(x, axis=1)) 
print ("sum by axis 2: ", np.sum(x, axis=2)) 

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
sum all:  42
sum by col:  [[ 2  4]
 [ 6  8]
 [10 12]]
sum by row:  [[ 9 12]
 [ 9 12]]
sum by ?:  [[ 3  7 11]
 [ 3  7 11]]


In [39]:
# Transposition
x = np.array([[1,2],[3,4]])
print("x:\n",x)
print("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


In [52]:
#np.tile
x = np.array([[1,2],[3,4]])
y = np.array([5,6])
addent = np.tile(y,(len(x),1)) #tile(the smallest element value, shape()) 
print("addent:\n", addent)
z = x + addent
print("z:\n",z)

addent:
 [[5 6]
 [5 6]]


In [66]:
#broadcasting
#During operation, always broadcast the smallest size element in order to match the bigger size element
x = np.array([[1,2],[3,4]])
y = np.array([5,6])
z = x + y
print("x+y:\n",z)
print("np.add(x,y):\n",np.add(x,y))

x+y:
 [[ 6  8]
 [ 8 10]]
np.add(x,y):
 [[ 6  8]
 [ 8 10]]


In [75]:
#Change the dimension
#As long as the size is the same
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print("x.shape: ", x.shape)
y = np.reshape(x,(2,3))
print("y.shape: ", y.shape)
print("y:\n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y:
 [[1 2 3]
 [4 5 6]]


In [82]:
#Delete dimension
#The size of deleted dimension must be 1
x = np.array([[[1,2,1]],[[2,2,3]]])
print("x.shape: ", x.shape)
y = np.squeeze(x,1) #delete dimension 1
print("y.shape: ", y.shape)
print("y:\n", y)

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y:
 [[1 2 1]
 [2 2 3]]


In [88]:
# Add dimension
x = np.array([[1,2,1],[2,2,3]])
print("x.shape: ", x.shape)
y = np.expand_dims(x,1) #insert dimension 1
print("y.shape: ", y.shape)
print("y:\n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y:
 [[[1 2 1]]

 [[2 2 3]]]


# 新段落

# 新段落