<a href="https://colab.research.google.com/github/LZY199/PracticalAI/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
SEED = 1234

# Set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

## **Basics**

In [16]:
# Creating a random tensor
x = torch.randn(2,3)
print("Type:", x.type())
print("Size:", x.shape)
print(f"Values:\n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values:
tensor([[ 0.6486,  1.7653,  1.0812],
        [ 1.2436,  0.8971, -0.0784]])


In [5]:
# Zero and Ones tensor
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# List -> Tensor
x = torch.Tensor([[1,2,3],[4,5,6]])
print(f"Size:{x.shape}")
print(f"Values:\n{x}")

Size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [20]:
# NumPy array -> Tensor
x = torch.Tensor(np.random.rand(2,3))
print(f"Size:{x.shape}")
print(f"Value:\n{x}")

Size:torch.Size([2, 3])
Value:
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [27]:
# Changing tensor type
x = torch.Tensor(3,4)
print(f"Type:{x.type()}")
print(x)
x = x.long()
print(f"Type:{x.type()}")
print(x)

Type:torch.FloatTensor
tensor([[6.6364e-01, 3.0726e-41, 3.3631e-44, 0.0000e+00],
        [       nan, 7.9984e+11, 4.4721e+21, 1.5956e+25],
        [4.7399e+16, 1.4917e-07, 6.1975e+26, 5.0583e+33]])
Type:torch.LongTensor
tensor([[                   0,                    0,                    0,
                            0],
        [-9223372036854775808,         799840141312, -9223372036854775808,
         -9223372036854775808],
        [   47399370747805696,                    0, -9223372036854775808,
         -9223372036854775808]])


## **Operations**

In [25]:
# Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print(f"Shape:{z.shape}")
print(f"Value;\n{z}")

Shape:torch.Size([2, 3])
Value;
tensor([[ 1.3794, -0.6568,  0.1027],
        [-0.8088, -2.8354, -0.0203]])


In [28]:
# Dot product
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print(f"Shape:{z.shape}")
print(f"Values:\n{z}")


Shape:torch.Size([2, 2])
Values:
tensor([[-3.5190,  1.6532],
        [-4.3273,  2.7265]])


In [29]:
# Transpose
x = torch.randn(2,3)
print(f"Shape:{x.shape}")
print(f"Values:\n{x}")
y = torch.t(x)
print(f"Shape:{y.shape}")
print(f"Values:\n{y}")

Shape:torch.Size([2, 3])
Values:
tensor([[-0.4572,  0.0901,  0.4018],
        [-1.1542,  0.1192, -0.7348]])
Shape:torch.Size([3, 2])
Values:
tensor([[-0.4572, -1.1542],
        [ 0.0901,  0.1192],
        [ 0.4018, -0.7348]])


In [32]:
# Reshape
x = torch.randn(2,3)
print(f"Shape:{x.shape}")
print(f"Values:\n{x}")
y = x.view(3,2)
print(f"Shape:{y.shape}")
print(f"Values:\n{y}")

Shape:torch.Size([2, 3])
Values:
tensor([[-0.6066, -0.4800,  1.1733],
        [ 0.3714, -2.3531, -1.6705]])
Shape:torch.Size([3, 2])
Values:
tensor([[-0.6066, -0.4800],
        [ 1.1733,  0.3714],
        [-2.3531, -1.6705]])


In [40]:
# Dangers of reshaping(unintended consequences)
x = torch.Tensor([[[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[10,10,10,10],[20,20,20,20],[30,30,30,30]]])
print(f"Size:{x.shape}")
print(f"Values:\n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize:{a.shape}")
print(f"Values:\n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize:{b.shape}")
print(f"Values:\n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize:{c.shape}")
print(f"Values:\n{c}\n")

Size:torch.Size([2, 3, 4])
Values:
tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.]],

        [[10., 10., 10., 10.],
         [20., 20., 20., 20.],
         [30., 30., 30., 30.]]])


Size:torch.Size([3, 8])
Values:
tensor([[ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3., 10., 10., 10., 10.],
        [20., 20., 20., 20., 30., 30., 30., 30.]])


Size:torch.Size([3, 2, 4])
Values:
tensor([[[ 1.,  1.,  1.,  1.],
         [10., 10., 10., 10.]],

        [[ 2.,  2.,  2.,  2.],
         [20., 20., 20., 20.]],

        [[ 3.,  3.,  3.,  3.],
         [30., 30., 30., 30.]]])


Size:torch.Size([3, 8])
Values:
tensor([[ 1.,  1.,  1.,  1., 10., 10., 10., 10.],
        [ 2.,  2.,  2.,  2., 20., 20., 20., 20.],
        [ 3.,  3.,  3.,  3., 30., 30., 30., 30.]])



In [43]:
# Dimensional operations
x = torch.randn(2,3)
print(f"Values:\n{x}")
y = torch.sum(x, dim=0)
print(f"Values:\n{y}")
z = torch.sum(x, dim=1)
print(f"Values:\n{z}")

Values:
tensor([[-1.3690,  0.5650,  0.4014],
        [ 1.3987,  0.7018, -0.4901]])
Values:
tensor([ 0.0297,  1.2668, -0.0887])
Values:
tensor([-0.4026,  1.6103])


## **Indexing**

In [44]:
x = torch.randn(3,4)
print(f"x:\n{x}")
print(f"x[:1]:\n{x[:1]}")
print(f"x[:1, 1:3]:\n{x[:1, 1:3]}")

x:
tensor([[ 0.4623, -2.1142, -1.0605,  0.4071],
        [ 1.3052,  0.4336, -1.0205,  1.7036],
        [ 0.7460,  0.9729, -0.9361,  0.7700]])
x[:1]:
tensor([[ 0.4623, -2.1142, -1.0605,  0.4071]])
x[:1, 1:3]:
tensor([[-2.1142, -1.0605]])


## **Slicing**