<a href="https://colab.research.google.com/github/LZY199/PracticalAI/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
SEED = 1234

# Set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

## **Basics**

In [3]:
# Creating a random tensor
x = torch.randn(2,3)
print("Type:", x.type())
print("Size:", x.shape)
print(f"Values:\n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values:
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [4]:
# Zero and Ones tensor
x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# List -> Tensor
x = torch.Tensor([[1,2,3],[4,5,6]])
print(f"Size:{x.shape}")
print(f"Values:\n{x}")

Size:torch.Size([2, 3])
Values:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# NumPy array -> Tensor
x = torch.Tensor(np.random.rand(2,3))
print(f"Size:{x.shape}")
print(f"Value:\n{x}")

Size:torch.Size([2, 3])
Value:
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [7]:
# Changing tensor type
x = torch.Tensor(3,4)
print(f"Type:{x.type()}")
print(x)
x = x.long()
print(f"Type:{x.type()}")
print(x)

Type:torch.FloatTensor
tensor([[1.0013e-20, 3.0737e-41, 3.0000e+00, 4.0000e+00],
        [5.0000e+00, 6.0000e+00, 1.3733e-14, 1.2102e+25],
        [1.6992e-07, 2.9599e+21, 2.8175e+20, 1.7566e+25]])
Type:torch.LongTensor
tensor([[                   0,                    0,                    3,
                            4],
        [                   5,                    6,                    0,
         -9223372036854775808],
        [                   0, -9223372036854775808, -9223372036854775808,
         -9223372036854775808]])


## **Operations**

In [8]:
# Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print(f"Shape:{z.shape}")
print(f"Value;\n{z}")

Shape:torch.Size([2, 3])
Value;
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [9]:
# Dot product
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print(f"Shape:{z.shape}")
print(f"Values:\n{z}")


Shape:torch.Size([2, 2])
Values:
tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])


In [10]:
# Transpose
x = torch.randn(2,3)
print(f"Shape:{x.shape}")
print(f"Values:\n{x}")
y = torch.t(x)
print(f"Shape:{y.shape}")
print(f"Values:\n{y}")

Shape:torch.Size([2, 3])
Values:
tensor([[ 0.8042, -0.1383,  0.3196],
        [-1.0187, -1.3147,  2.5228]])
Shape:torch.Size([3, 2])
Values:
tensor([[ 0.8042, -1.0187],
        [-0.1383, -1.3147],
        [ 0.3196,  2.5228]])


In [11]:
# Reshape
x = torch.randn(2,3)
print(f"Shape:{x.shape}")
print(f"Values:\n{x}")
y = x.view(3,2)
print(f"Shape:{y.shape}")
print(f"Values:\n{y}")

Shape:torch.Size([2, 3])
Values:
tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702]])
Shape:torch.Size([3, 2])
Values:
tensor([[ 0.4501,  0.2709],
        [-0.8087, -0.0217],
        [-1.0413,  0.0702]])


In [12]:
# Dangers of reshaping(unintended consequences)
x = torch.Tensor([[[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[10,10,10,10],[20,20,20,20],[30,30,30,30]]])
print(f"Size:{x.shape}")
print(f"Values:\n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize:{a.shape}")
print(f"Values:\n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize:{b.shape}")
print(f"Values:\n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize:{c.shape}")
print(f"Values:\n{c}\n")

Size:torch.Size([2, 3, 4])
Values:
tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.]],

        [[10., 10., 10., 10.],
         [20., 20., 20., 20.],
         [30., 30., 30., 30.]]])


Size:torch.Size([3, 8])
Values:
tensor([[ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3., 10., 10., 10., 10.],
        [20., 20., 20., 20., 30., 30., 30., 30.]])


Size:torch.Size([3, 2, 4])
Values:
tensor([[[ 1.,  1.,  1.,  1.],
         [10., 10., 10., 10.]],

        [[ 2.,  2.,  2.,  2.],
         [20., 20., 20., 20.]],

        [[ 3.,  3.,  3.,  3.],
         [30., 30., 30., 30.]]])


Size:torch.Size([3, 8])
Values:
tensor([[ 1.,  1.,  1.,  1., 10., 10., 10., 10.],
        [ 2.,  2.,  2.,  2., 20., 20., 20., 20.],
        [ 3.,  3.,  3.,  3., 30., 30., 30., 30.]])



In [13]:
# Dimensional operations
x = torch.randn(2,3)
print(f"Values:\n{x}")
y = torch.sum(x, dim=0)
print(f"Values:\n{y}")
z = torch.sum(x, dim=1)
print(f"Values:\n{z}")

Values:
tensor([[ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189]])
Values:
tensor([-0.1000, -0.3166, -1.6373])
Values:
tensor([ 0.7013, -2.7553])


## **Indexing**

In [14]:
x = torch.randn(3,4)
print(f"x:\n{x}")
print(f"x[:1]:\n{x[:1]}")
print(f"x[:1, 1:3]:\n{x[:1, 1:3]}")

x:
tensor([[ 0.2111,  0.3372,  0.6638,  1.0397],
        [ 1.8434,  0.6588, -0.2349, -0.0306],
        [ 1.7462, -0.0722, -1.6794, -1.7010]])
x[:1]:
tensor([[0.2111, 0.3372, 0.6638, 1.0397]])
x[:1, 1:3]:
tensor([[0.3372, 0.6638]])


## **Slicing**

In [20]:
# Select twith dimensional indices
x = torch.randn(2,3)
print(f"Values:\n{x}")

col_indices = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim=1, index=col_indices)
print(f"Values:\n{chosen}")

row_indices = torch.LongTensor([0,1])
col_indices = torch.LongTensor([0,2])
chosen = x[row_indices, col_indices]
print(f"Values:\n{chosen}")


Values:
tensor([[-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259]])
Values:
tensor([[-0.3449,  0.0685],
        [-1.5104,  0.2259]])
Values:
tensor([-0.3449,  0.2259])


## **Joining**

In [24]:
# Concatenation
x = torch.Tensor(2,3)
print(f"Values:\n{x}")
x = torch.cat([x,x], dim=0)
print(f"Values;\n{x}")

Values:
tensor([[1.6796e-20, 3.0737e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])
Values;
tensor([[1.6796e-20, 3.0737e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.6796e-20, 3.0737e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


## **Gradients**

In [28]:
# Tensors with gradient bookkeeping
x = torch.rand(3,4,requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()
print(f"x:\n{x}")
print(f"x.grad:\n{x.grad}")


x:
tensor([[0.2008, 0.5610, 0.4073, 0.6077],
        [0.3811, 0.1727, 0.5664, 0.8386],
        [0.1998, 0.9383, 0.6231, 0.9930]], requires_grad=True)
x.grad:
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


## **CUDA**

In [29]:
#Is CUDA available
print(torch.cuda.is_available())

False


In [1]:
import torch
#Is CUDA availabe
print(torch.cuda.is_available())

True


In [3]:
# Set device
device= torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [5]:
x = torch.rand(2,3)
print(x.is_cuda)
x = torch.rand(2,3).to(device) #Tensor is stored in the GPU
print(x.is_cuda)

False
True
